server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    # AGGRESSIVE TUNING FOR 15S DEMO BUDGET
    # Flush logs to Loki every 100ms or when batch hits 100KB
    batchwait: 100ms
    batchsize: 102400

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 1s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'app'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{app=~".+"}'
          stages:
            - json:
                expressions:
                  msg: message
                  level: level
                  traceID: traceID
                  spanID: spanID
            - labels:
                level:
                traceID:
      - output:
          source: msg
